### ISSUE TITLE
请大佬赐一份非hass插件代码

### ISSUE THREAD

**Issue by swpu-cxm** [Zrincet/MiPhone_tracker#1]
大佬可否传一份非hass插件的py代码，能单独跑那种，想自己定制一些其他功能，主要是想要登陆模块的代码，hass插件里面的代码看不太明白，感谢不尽。

**Comment by Zrincet** [comment]
参考_get_sign _serviceLoginAuth2 _login_miai这三个方法，稍微改一下就可以直接跑了

**Comment by swpu-cxm** [comment]
https://account.xiaomi.com/pass/serviceLogin?sid%3Di.mi.com&sid=i.mi.com&_locale=zh_CN&_snsNone=true这个url好像不能访问呢，还有请问deviceChoose，coordinate_type，captCode这三个参数分别是干什么的呢

**Comment by Zrincet** [comment]
_get_sign 获取 sign， _serviceLoginAuth2 通过sign 获取另外一些参数 _login_miai通过之前获得的参数 得到Service_Token和userId

**Comment by swpu-cxm** [comment]
恩，您说的这些我大概看懂了，就是想问一下deviceChoose，coordinate_type，captCode，这个三个参数分别对应着什么，还有_get_sign的url   https://account.xiaomi.com/pass/serviceLogin?sid%3Di.mi.com&sid=i.mi.com&_locale=zh_CN&_snsNone=true  好像不能访问了

**Comment by Zrincet** [comment]
https://account.xiaomi.com/pass/serviceLogin?sid%3Di.mi.com&sid=i.mi.com&_locale=zh_CN&_snsNone=true 不是让你从浏览器访问的，只是要拿相关参数用的 ，参数见https://bbs.hassbian.com/thread-10545-1-2.html

**Comment by swpu-cxm** [comment]
终于调通了，请问楼主是python啥版本啊，requests包的好多写法和3.8不一样呢
